import React, { useState, useEffect } from "react";

const ProductGrid = () => {
  const [products, setProducts] = useState([]);

  useEffect(() => {
    const getNewArrivals = async () => {
      try {
        const response = await fetch(
          "http://localhost/master_tubes_website_api/api/product.php",
          {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
            },
            // Your backend requires these fields to trigger the READ action
            body: JSON.stringify({
              company_id: "COMP-000001",
              fetch_all: true,
            }),
          }
        );

        const data = await response.json();

        if (data.head.code === 200) {
          // CONDITION: Filter only products where new_arrival is NOT 0
          const arrivals = data.body.products.filter(
            (product) => product.new_arrival !== 0
          );
          setProducts(arrivals);
        }
      } catch (error) {
        console.error("Error fetching products:", error);
      }
    };

    getNewArrivals();
  }, []);

  return (
    <section>
      <div className="parent">
        {products.map((item, index) => (
          <div
            key={item.id}
            className="product-card"
            data-aos="zoom-in"
            data-aos-delay={index * 100}
            data-aos-duration="800"
          >
            <div>
              {/* Uses the product_img_url generated by your backend */}
              <img src={item.product_img_url} alt={item.product_name} />
            </div>
            <div>
              <h4>{item.product_name}</h4>
              <button className="shop_now">Shop Now</button>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
};

export default ProductGrid;
